#!/bin/bash
file=$1

#Check if file name is provided
if [ ! $file ]; then
    echo "Sorry, filename needed. Try again."
    exit 1
else
    touch $file
    chmod 744 $file
    echo "Script $file created"
    read -p "Open with: " editor
    if [ $editor ]; then
	echo "#!/bin/bash" > $file
	$editor $file
    fi
fi
