#!/bin/bash
file=$1
editor=$EDITOR

#If filename not provided, prompt notify and exit.
#Else create file, and add x permission
#If default editor not set then get it from user and use to open file.

if [ ! $file ]; then
    echo "Sorry, filename needed. Try again."
    exit 1
else
    touch $file
    chmod 744 $file
    echo "#!/bin/bash" > $file
    echo "Script $file created"
    
    if [ ! $editor ]; then
	read -p "Set your default editor: " edtr
	export EDITOR=$edtr
	editor=$EDITOR
    fi
    $editor $file
fi
